"""
agent/llm_agent_langchain.py

LangChain-powered report generator using Claude (claude-opus-4-8).

LangChain features used
------------------------
1. ChatAnthropic          – official LangChain wrapper for Anthropic / Claude
2. ChatPromptTemplate     – reusable prompt with named {variables}
3. LCEL pipe operator (|) – chains prompt → LLM → parser in one expression
4. StrOutputParser        – extracts the plain-text reply from the LLM response
5. RunnableLambda         – wraps the rule-based fallback as a LangChain Runnable
6. RunnableWithFallbacks  – automatically retries with the fallback Runnable on error
"""

from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda

from config import ANTHROPIC_API_KEY, CLAUDE_MODEL


# ─── helpers ────────────────────────────────────────────────────────────────

def _silhouette_label(score: float) -> str:
    if score >= 0.5:
        return "good"
    if score >= 0.25:
        return "moderate"
    return "weak"


def _rule_based_report(inputs: dict) -> str:
    """
    Pure-Python fallback that generates a structured report from raw metrics.
    Wrapped as a LangChain RunnableLambda so it fits seamlessly into the chain.
    """
    analysis          = inputs["analysis"]
    supervised        = inputs["supervised_results"] or {}
    best_model        = inputs["best_model"] or ""
    clustering        = inputs["clustering_results"]

    rows          = analysis.get("num_rows", "?")
    cols          = analysis.get("num_cols", "?")
    target        = analysis.get("target_column", "?")
    size          = analysis.get("size", "?")
    missing_ratio = analysis.get("missing_ratio", 0)
    n_classes     = analysis.get("target_unique_values", "?")

    ranked = sorted(
        supervised.items(),
        key=lambda x: x[1].get("mean", 0),
        reverse=True,
    )

    best_m   = supervised.get(best_model, {})
    best_f1  = best_m.get("mean", 0)
    best_std = best_m.get("std", 0)

    k_score = clustering["kmeans"]["silhouette_score"]
    h_score = clustering["hierarchical"]["silhouette_score"]
    best_c  = clustering["best"]

    lines = [
        "# AI Data Scientist — Analysis Report (LangChain Rule-Based Fallback)",
        "",
        "## 1. Dataset Overview",
        f"- **Rows:** {rows}  |  **Features:** {cols}  |  **Size:** {size}",
        f"- **Target:** `{target}`  |  **Classes:** {n_classes}",
        f"- **Missing values:** {missing_ratio * 100:.1f}%",
        "",
        "## 2. Best Model",
        f"**{best_model}** — Mean F1 = {best_f1:.4f}, Std = {best_std:.4f}",
        "",
        "## 3. Model Comparison",
        "| Rank | Model | Mean F1 | Std |",
        "|------|-------|---------|-----|",
    ]
    for i, (name, m) in enumerate(ranked, 1):
        marker = " ★" if name == best_model else ""
        lines.append(f"| {i} | {name}{marker} | {m.get('mean',0):.4f} | {m.get('std',0):.4f} |")

    lines += [
        "",
        "## 4. Clustering Quality",
        f"| Algorithm | Silhouette | Quality |",
        f"|-----------|-----------|---------|",
        f"| K-Means | {k_score:.4f} | {_silhouette_label(k_score).capitalize()} |",
        f"| Hierarchical | {h_score:.4f} | {_silhouette_label(h_score).capitalize()} |",
        f"",
        f"**Best:** {best_c}",
        "",
        "---",
        "*Report generated by the rule-based fallback (Anthropic API unavailable).*",
    ]
    return "\n".join(lines)


# ─── LangChain chain ─────────────────────────────────────────────────────────

# FEATURE 1 – ChatAnthropic: official LangChain LLM wrapper for Claude
_llm = ChatAnthropic(
    model=CLAUDE_MODEL,
    api_key=ANTHROPIC_API_KEY,
    max_tokens=2048,
)

# FEATURE 2 – ChatPromptTemplate: system + human message template with {variables}
_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        (
            "You are an expert AI Data Scientist. "
            "Produce a well-structured markdown report that covers: "
            "(1) why the best model was selected with exact metric values, "
            "(2) comparison of all models trained, "
            "(3) clustering quality analysis (silhouette >0.5 = good, 0.25–0.5 = moderate, <0.25 = poor), "
            "(4) concrete recommendations, "
            "(5) suggested next steps. "
            "Use numbered sections and bullet points."
        ),
    ),
    (
        "human",
        (
            "TASK: {task}\n\n"
            "DATASET ANALYSIS:\n{analysis}\n\n"
            "SUPERVISED LEARNING RESULTS:\n{supervised_results}\n\n"
            "BEST MODEL: {best_model}\n\n"
            "CLUSTERING RESULTS:\n{clustering_results}"
        ),
    ),
])

# FEATURE 3 – StrOutputParser: extracts the text string from the ChatMessage response
_parser = StrOutputParser()

# FEATURE 4 – LCEL pipe operator (|): chains prompt → LLM → parser declaratively
_chain = _prompt | _llm | _parser

# FEATURE 5 – RunnableLambda: wraps a plain Python function as a LangChain Runnable
_fallback_runnable = RunnableLambda(_rule_based_report)

# FEATURE 6 – RunnableWithFallbacks: if _chain raises any exception, automatically
#              retries with _fallback_runnable using the same input dict
_chain_with_fallback = _chain.with_fallbacks([_fallback_runnable])


# ─── public API ──────────────────────────────────────────────────────────────

def generate_agent_report(
    task,
    analysis,
    supervised_results,
    best_model,
    clustering_results,
) -> str:
    """
    Generate a natural-language report via the LangChain + Claude chain.

    The chain executes:
        ChatPromptTemplate  →  ChatAnthropic (claude-opus-4-8)  →  StrOutputParser

    If the Anthropic API is unavailable or the key is missing, RunnableWithFallbacks
    transparently switches to the rule-based _fallback_runnable and returns the
    locally-generated report — so the frontend always receives a complete result.
    """
    inputs = {
        "task":               str(task).upper(),
        "analysis":           str(analysis),
        "supervised_results": str(supervised_results),
        "best_model":         str(best_model),
        "clustering_results": str(clustering_results),
    }

    print(f"[LangChain] Invoking chain: ChatPromptTemplate | ChatAnthropic({CLAUDE_MODEL}) | StrOutputParser")
    report = _chain_with_fallback.invoke(inputs)
    print("[LangChain] Report generated.")
    return report
